package com.github.hemoptysisheart.parking.core.client.google.dto

import java.net.URL

data class PlaceDto(
    val addressComponents: List<AddressComponentDto>?,
    val adrAddress: String?,
    val businessStatus: BusinessStatus?,
    val curbsidePickup: Boolean?,
    val currentOpeningHours: PlaceOpeningHoursDto?,
    val delivery: Boolean?,
    val dineIn: Boolean?,
    val editorialSummary: PlaceEditorialSummaryDto?,
    val formattedAddress: String?,
    val formattedPhoneNumber: String?,
    val geometry: GeometryDto?,
    val icon: URL?,
    val iconBackgroundColor: String?,
    val iconMaskBase: URL?,
    val internationalPhoneNumber: String?,
    val name: String,
    val openingHours: PlaceOpeningHoursDto?,
    val photos: List<PlacePhotoDto>?,
    val placeId: String?,
    val plusCode: PlusCodeDto?,
    val priceLv: PriceLevel?,
    val rating: Double?,
    val reservable: Boolean?,
    val reviews: List<PlaceReviewDto>?,
    val secondaryOpeningHours: PlaceOpeningHoursDto?,
    val beer: Boolean?,
    val breakfast: Boolean?,
    val brunch: Boolean?,
    val dinner: Boolean?,
    val lunch: Boolean?,
    val vegetarianFood: Boolean?,
    val wine: Boolean?,
    val takeout: Boolean?,
    val types: Set<PlaceType>?,
    val url: URL?,
    val userRatingsTotal: Int?,
    val utcOffset: Int?,
    val vicinity: String?,
    val website: URL?,
    val wheelchairAccessibleEntrance: Boolean?
)
