name: CI - Pull Request
on:
  pull_request_target:
    # Sequence of patterns matched against refs/heads
    branches:
      - test-main
jobs:
  ci:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Prepare Files
        run: |
          echo GOOGLE_MAPS_PLATFORM_API_KEY=${{ secrets.GOOGLE_MAPS_PLATFORM_API_KEY }} >> local.properties
      - name: Build `debug` AAB
        run: ./gradlew clean :app:bundleDebug
      - name: Create Tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: build/${GITHUB_RUN_NUMBER}
          message: 'PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'
      - name: Prepare Deploy
        run: |
          mkdir workflow
          cp app/build/outputs/bundle/debug/app-debug.aab workflow/parking-debug-${GITHUB_RUN_NUMBER}.aab
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: workflow/parking-debug-${GITHUB_RUN_NUMBER}.aab
