name: CI - Pull Request
on:
  pull_request_target:
    # Sequence of patterns matched against refs/heads
    branches:
      - test-main
    types:
      - closed
jobs:
  ci:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Prepare Files
        run: |
          echo GOOGLE_MAPS_PLATFORM_API_KEY=${{ secrets.GOOGLE_MAPS_PLATFORM_API_KEY }} >> local.properties
      #- name: Build `debug` AAB
      #  run: ./gradlew clean :app:bundleDebug
      - name: Prepare Deploy
        run: |
          mkdir workflow
          #cp app/build/outputs/bundle/debug/app-debug.aab workflow/parking-debug-${GITHUB_RUN_NUMBER}.aab
          # TODO delete
          touch workflow/parking-debug-${GITHUB_RUN_NUMBER}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Tag
        run: |
          git tag "nightly/${GITHUB_RUN_NUMBER}"
          git push origin "nightly/${GITHUB_RUN_NUMBER}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: workflow/parking-debug-${GITHUB_RUN_NUMBER}.aab
