name: CI
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Prepare config file(s).
        run: echo GOOGLE_MAPS_PLATFORM_API_KEY=${{ secrets.GOOGLE_MAPS_PLATFORM_API_KEY }} >> local.properties
      - name: Unit Test
        run: ./gradlew clean :util:test :domain:test testDebugUnitTest --continue
      # - name: Create `tag`
      #   run: echo 'TODO create tag'
      # - name: Build debug AAB
      #   run: echo 'TODO build debug aab.' #./gradlew :app:bundleDebug
      - name: Prepare Unit Test Reports
        run: |
          mkdir -pv public
          cp .github/workflows/test-reports-index.html index.html
          cp -Rv util/build/reports/tests/test public/util
          # cp -Rv client-google/build/reports/tests/test public/client-google
          cp -Rv domain/build/reports/tests/test public/domain
          # cp -Rv core/build/reports/tests/test public/core
          # cp -Rv app/build/reports/tests/test public/app
      - name: Deploy Unit Test Reports
        uses: w9jds/firebase-action@master
        with:
          args: |
            hosting:channel:deploy ci_${{ vars.GITHUB_RUN_NUMBER }} --expires 7d
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PARKING_367004 }}'
      - name: Unit Test Reports
        run: firebase hosting:channel:open ci_${{ vars.GITHUB_RUN_NUMBER }}
