name: CI
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Prepare Config File(s).
        run: |
          echo GOOGLE_MAPS_PLATFORM_API_KEY=${{ secrets.GOOGLE_MAPS_PLATFORM_API_KEY }} >> local.properties
      - name: Run Unit Test
        run: ./gradlew clean :util:test :domain:test testDebugUnitTest --continue
      # - name: Create `tag`
      #   run: echo 'TODO create tag'
      # - name: Build debug AAB
      #   run: echo 'TODO build debug aab.' #./gradlew :app:bundleDebug
      - name: Prepare Unit Test Reports
        run: |
          mkdir -pv public
          cp .github/workflows/test-reports-index.html public/index.html
          cp -R util/build/reports/tests/test public/util
          # TODO cp -Rv client-google/build/reports/tests/test public/client-google
          cp -R domain/build/reports/tests/test public/domain
          # TODO cp -Rv core/build/reports/tests/test public/core
          # TODO cp -Rv app/build/reports/tests/test public/app
      - name: Deploy Unit Test Reports
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy ci_${GITHUB_RUN_NUMBER} --expires 10d
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PARKING_367004 }}'
      - name: Unit Test Reports
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:open ci_${GITHUB_RUN_NUMBER}  >> test-report.txt
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PARKING_367004 }}'
      - name: Load UT Report URL
        id: report_url
        run: |
          echo "url=$(cat test-report.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" |\
            tr -d '\n' | tr -d '"' | jq -Rsa . )" >> $GITHUB_OUTPUT
      - name: Comment UT Report URL to Commit
        run: |
          echo "comment : ${{ steps.report_url.outputs.url }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hemoptysisheart/parking-android/commits/${{ github.sha }}/comments \
            -d "{ \"body\":\"${{ steps.report_url.outputs.url }}\" }"
